server:
  port: 8080
logging:
  level:
    root: INFO
#    org.hibernate.sql: debug
#    org.hibernate.jdbc.bind: trace

#spring:
#  jpa:
#    generate-ddl: false
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    properties:
#      hibernate:
#        format_sql: true
#        highlight_sql: true
#        use_sql_comments: false
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        show_sql: true
#    # OSIV ????
#    open-in-view: false
